#!/bin/bash

die() {
    echo "$*" 1>&2
    exit 1
}

test -d ./venv || die "run ./setup-venv first"
source ./venv/bin/activate
xdpyinfo 2>/dev/null 1>&2 || BROWSER="--no-browser"
jupyter notebook $BROWSER
